project_name/apps/app1/urls.py
from django.conf.urls import patterns, url

from app1 import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^logout', views.logout_view, name='logout'),
    url(r'^profile', views.profile, name='profile'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^privacy', views.privacy, name='privacy'),
    url(r'^terms', views.terms, name='terms'),
)

project_name/project_dir/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Account registration URLs
    url(r'^accounts/', include(
            'registration.backends.default.urls',
            namespace='accounts',
            app_name='accounts'
        ),
        name='registration_register',
    ),

    # Social Auth URLs
    url('s-auth/', include(
        'social.apps.django_app.urls',
        namespace='social'
    )),

    # Django Auth URLs
    url('auth/', include(
        'django.contrib.auth.urls',
        namespace='auth',
        app_name='auth'
    )),

    # Load the admin urls
    url(r'^admin/', include(admin.site.urls)),

    # Default to SDC urls
    url(r'', include(
        'app1.urls',
        namespace='app1',
        app_name='app1'
    )),
)

project_name/apps/app1/models.py
from django.db import models

# Create your models here.

project_name/apps/app1/views.py
import sys

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth import logout


def index(request):
    context = {}
    return render(request, 'app1/index.html', context)


def logout_view(request):
    logout(request)
    return redirect('app1:index')


def profile(request):
    context = {}
    return render(request, 'app1/profile.html', context)


def about(request):
    context = {}
    return render(request, 'app1/about.html', context)


def contact(request):
    context = {}
    return render(request, 'app1/contact.html', context)


def privacy(request):
    context = {}
    return render(request, 'app1/privacy.html', context)


def terms(request):
    context = {}
    return render(request, 'app1/terms.html', context)

project_name/apps/app1/templates/app1/about.html
{% extends "index.html" %}

{% block page_block %}
<div class="row">
  <div class="container marketing">
    <!-- START THE FEATURETTES -->
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">PROJECT_NAME</h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-responsive" src="https://placeimg.com/500/500/tech" alt="Generic placeholder image">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-5">
        <img class="featurette-image img-responsive" src="https://placeimg.com/500/500/tech" alt="Generic placeholder image">
      </div>
      <div class="col-md-7">
        <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-responsive" src="https://placeimg.com/500/500/tech" alt="Generic placeholder image">
      </div>
    </div>

    <hr class="featurette-divider">
  </div>
  <!-- /END THE FEATURETTES -->

</div><!-- /.container -->
{% endblock %}

project_name/apps/app1/templates/app1/contact.html
{% extends "index.html" %}

{% block page_block %}
  <div class="row">
    <div class="container">
      <div class="jumbotron">
        <h1>Contact PROJECT_NAME</h1>
        <p class="lead">
          PROJECT_NAME would like to hear from you.
        </p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>PROJECT_NAME people</h4>
          <p>
            Chad Rempp - <a href="mailto:crempp@gmail.com">crempp@gmail.com</a>
          </p>

          <h4>PROJECT_NAME places</h4>
          <p>none yet</p>
        </div>

      </div>
    </div>

  </div>
{% endblock %}

project_name/apps/app1/templates/app1/index.html
{% extends "index.html" %}

{% block page_block %}
<!-- Carousel===================================== -->
<div class="row">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="https://placeimg.com/1600/500/tech" alt="First slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>PROJECT_NAME</h1>
            <p>
              Disrupting the new social paradigm - Locally
            </p>
          </div>
        </div>
      </div>
      <div class="item">
        <img src="https://placeimg.com/1601/500/tech" alt="Second slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          </div>
        </div>
      </div>
      <div class="item">
        <img src="https://placeimg.com/1602/500/tech" alt="Third slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>One more for good measure.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          </div>
        </div>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div><!-- /.carousel -->
</div>

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="row">
  <div class="container marketing">
    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">PROJECT_NAME</h2>
        <p class="lead">
          Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
        </p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-responsive" src="https://placeimg.com/500/500/tech" alt="Generic placeholder image">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-5">
        <img class="featurette-image img-responsive" src="https://placeimg.com/500/500/tech" alt="Generic placeholder image">
      </div>
      <div class="col-md-7">
        <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-responsive" src="https://placeimg.com/500/500/tech" alt="Generic placeholder image">
      </div>
    </div>

    <hr class="featurette-divider">
  </div>
  <!-- /END THE FEATURETTES -->

</div><!-- /.container -->

{% endblock %}

project_name/apps/app1/templates/app1/privacy.html
{% extends "index.html" %}

{% block page_block %}
  <div class="row">
    <p>privacy</p>

    sdfasdf
  </div>
{% endblock %}

project_name/apps/app1/templates/app1/profile.html
{% extends "index.html" %}

{% block page_block %}
  <div class="row">
    <p>Profile</p>
    sdfasdf
  </div>
{% endblock %}

project_name/apps/app1/templates/app1/terms.html
{% extends "index.html" %}

{% block page_block %}
  <div class="row">
    <p>terms of service</p>

    sdfasdf
  </div>
{% endblock %}

project_name/templates/index.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PROJECT_NAME</title>
    <meta name="description" content="PROJECT_DESCRIPTION">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{% static "apple-touch-icon.png" %}">
    <!-- Place favicon.ico in the root directory -->

    {% if minified_assets %}
    <link rel="stylesheet" href="{% static "css/app.min.css" %}">
    {% else %}
    <link rel="stylesheet" href="{% static "css/app.css" %}">
    {% endif %}
  </head>
<body>
  <!-- Begin Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top">{% include "navigation.html" %}</nav>
  <!-- End Navigation -->

  <!-- TODO: Put this in a flash box -->
  <!--[if lt IE 8]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->

  <!-- Begin Page Content -->
  <div class="container-fluid">
    {% block page_block %}{% endblock %}
  </div>
  <!-- Begin Page Content -->

  <!-- FOOTER -->
  <footer class="footer">
    <div class="container">
      <p>&copy; 2015 LapinLabs
        &middot; <a href="{% url 'app1:privacy' %}">Privacy</a>
        &middot; <a href="{% url 'app1:terms' %}">Terms</a></p>
    </div>
  </footer>

  {% if minified_assets %}
  {% include "vendor-build.html" %}
  {% else %}
  {% include "vendor-build.html" %}
  {% endif %}

  {% if do_analytics %}
  <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
  <script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
  </script>
  {% endif %}
</body>
</html>

project_name/templates/navigation.html
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'app1:index' %}">NewProject</a>
  </div>
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><a href="{% url 'app1:about' %}">About</a></li>
      <li><a href="{% url 'app1:contact' %}">Contact</a></li>
      <!--
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Nav header</li>
          <li><a href="#">Separated link</a></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
      -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li><a href="{% url 'app1:profile' %}">profile</a></li>
      <li><a href="{% url 'app1:logout' %}">logout</a></li>
      {% else %}
      {# <li><a href="{% url 'registration_register' %}">register</a></li>#}
      <li><a href="{% url 'auth:login' %}">login</a></li>
      {% endif %}
    </ul>
  </div><!--/.nav-collapse -->
</div><!--/.container-fluid -->

project_name/templates/vendor-build.html
<!-- inject:css -->
<link rel="stylesheet" href="/static/css/vendor/bootstrap.css">
<link rel="stylesheet" href="/static/css/vendor/font-awesome.css">
<!-- endinject -->

<!-- inject:js -->
<script src="/static/js/vendor/jquery.min.js"></script>
<script src="/static/js/vendor/underscore.min.js"></script>
<script src="/static/js/vendor/bootstrap.min.js"></script>
<script src="/static/js/vendor/normalize.min.js"></script>
<script src="/static/js/vendor/backbone.min.js"></script>
<script src="/static/js/vendor/jquery.smartmenus.min.js"></script>
<!-- endinject -->

project_name/templates/vendor-src.html
<!-- inject:css -->
<!-- endinject -->

<!-- inject:js -->
<!-- endinject -->